## check development version of mboost
## see http://docs.travis-ci.com/user/languages/r/

language: r

before_install:
  - cd pkg/mboostDevel

r_github_packages:
  - hofnerb/stabs
  
after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
