# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - mkdir src
  - ps: Bootstrap

# Adapt as necessary starting from here

# environment:
#   matrix:
#   - TEST_DIR: pkg\mboostPatch
#   - TEST_DIR: pkg\mboostDevel

before_build:
#   - cp travis-tool.sh.cmd %TEST_DIR%/travis-tool.sh.cmd
#   - cp ../travis-tool.sh pkg/travis-tool.sh
#   - cd %TEST_DIR%
  - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs
  - appveyor PushArtifact C:/projects/mboost/mboost.Rcheck/00install.out
  - cat C:/projects/mboost/mboost.Rcheck/00install.out

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '*_*.tar.gz'
    name: Bits

  - path: '*_*.zip'
    name: Bits
