# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  matrix:
  - TEST_DIR: pkg\mboostPatch
  - TEST_DIR: pkg\mboostDevel

before_build:
  - cp travis-tool.sh.cmd %TEST_DIR%/travis-tool.sh.cmd
  - cp ../travis-tool.sh pkg/travis-tool.sh
  - cd %TEST_DIR%
  - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '$(TEST_DIR)\*.Rcheck\**\*.log'
    name: Logs

  - path: '$(TEST_DIR)\*.Rcheck\**\*.out'
    name: Logs

  - path: '$(TEST_DIR)\*.Rcheck\**\*.fail'
    name: Logs

  - path: '$(TEST_DIR)\*.Rcheck\**\*.Rout'
    name: Logs

  - path: '$(TEST_DIR)\*_*.tar.gz'
    name: Bits

  - path: '$(TEST_DIR)\*_*.zip'
    name: Bits